---
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    environment_name: production
  children:
    glpi_app:
      hosts:
        prd-app:
          ansible_host: 192.0.2.30
    glpi_db:
      hosts:
        prd-db:
          ansible_host: 192.0.2.40
