---
glpi_version: "11.0.0"
glpi_download_url: "https://github.com/glpi-project/glpi/releases/download/{{ glpi_version }}/glpi-{{ glpi_version }}.tgz"
glpi_release_root: /usr/share
glpi_release_dir: "{{ glpi_release_root }}/glpi-{{ glpi_version }}"
glpi_install_dir: /usr/share/glpi
glpi_config_dir: /etc/glpi
glpi_var_dir: /var/lib/glpi/files
glpi_plugin_dir: /var/lib/glpi/plugins
glpi_log_dir: /var/log/glpi
glpi_data_owner: www-data
glpi_data_group: www-data
glpi_domain: servicedesk.soenergy.com
glpi_use_tls: true
glpi_tls_mode: provided
glpi_tls_certificate_path: /etc/ssl/certs/glpi-production.crt
glpi_tls_certificate_key_path: /etc/ssl/private/glpi-production.key
glpi_tls_common_name: servicedesk.soenergy.com
glpi_tls_provided_local_cert_path: ""
glpi_tls_provided_local_key_path: ""
glpi_php_fpm_service: php8.3-fpm
glpi_php_fpm_socket: /run/php/php8.3-fpm.sock
glpi_app_packages:
  - nginx
  - php-fpm
  - php-cli
  - php-curl
  - php-gd
  - php-intl
  - php-mbstring
  - php-mysql
  - php-xml
  - php-zip
  - php-bz2
  - php-apcu
  - php-ldap
  - php-imap
  - php-opcache
  - php-redis
  - tar
  - xz-utils
  - curl
glpi_upload_max_filesize: 64M
glpi_post_max_size: 64M
glpi_memory_limit: 1024M
glpi_max_execution_time: 120
glpi_opcache_memory_consumption: 256
glpi_pm: dynamic
glpi_pm_max_children: 50
glpi_pm_start_servers: 8
glpi_pm_min_spare_servers: 4
glpi_pm_max_spare_servers: 12
glpi_pm_max_requests: 500
glpi_cron_schedule: "*/5 * * * *"
glpi_backup_base_dir: /var/backups/glpi
glpi_backup_retention_days: 30
node_exporter_enabled: true
mysqld_exporter_enabled: true
mariadb_bind_address: 0.0.0.0
mariadb_port: 3306
mariadb_version_packages:
  - mariadb-server
  - mariadb-client
  - python3-pymysql
mariadb_innodb_buffer_pool_size: 24G
mariadb_max_connections: 180
mariadb_tmp_table_size: 256M
mariadb_max_heap_table_size: 256M
mariadb_slow_query_log: 1
mariadb_long_query_time: 2
timezone_name: America/Sao_Paulo
db_allowed_source_hosts:
  - 192.0.2.30
glpi_db_app_access_host: 192.0.2.30
