---
- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Restart php-fpm
  ansible.builtin.service:
    name: "{{ glpi_php_fpm_service }}"
    state: restarted

- name: Reload apache2
  ansible.builtin.service:
    name: "{{ glpi_apache_service | default('apache2') }}"
    state: reloaded

- name: Reload lighttpd
  ansible.builtin.service:
    name: lighttpd
    state: reloaded
